name: Release
on:
  # manual trigger
  workflow_dispatch:

jobs:
  publish:
    name: Publicar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pin to IPFS
        id: upload
        uses: aquiladev/ipfs-action@master
        with:
          pinName: biokaos-dcentralized
          path: './w3-mibalx'
          service: pinata
          pinataKey: ${{ secrets.PINATA_API_KEY }}
          pinataSecret: ${{ secrets.PINATA_API_SECRET_KEY }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1
          release_name: Release v1
          body: |
            IPFS hash of the deployment:
            - CIDv0: `${{ steps.upload.outputs.hash }}`
            - CIDv1: `${{ steps.upload.outputs.cid }}`
            - IPNS: `${{ steps.upload.outputs.ipns }}`

            You can access the game directly from an IPFS gateway.

            Preferred URLs:
            - https://${{ steps.upload.outputs.cid }}.ipfs.dweb.link/
            - [ipfs://${{ steps.upload.outputs.hash }}/](ipfs://${{ steps.upload.outputs.hash }}/)

            Other IPFS gateways:
            - https://ipfs.io/ipfs/${{ steps.upload.outputs.hash }}
