name: Release
on:
  # manual trigger
  workflow_dispatch:

jobs:
  publish:
    name: Publicar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pin to Pinata IPFS
        id: upload-pinata
        uses: mibaltoalex/ipfs-action@master
        with:
          pinName: biokaos-dcentralized
          path: './w3-mibalx'
          service: pinata
          pinataKey: ${{ secrets.PINATA_API_KEY }}
          pinataSecret: ${{ secrets.PINATA_API_SECRET_KEY }}
          
      - name: Pin to DWEB IPFS
        id: upload-dweb
        uses: mibaltoalex/ipfs-action@master
        with:
          host: ipfs.io
          key: ${{ steps.upload-pinata.outputs.cid }}
          path: './w3-mibalx'
          service: ipfs
          
      - run: echo "ipfs:${{ steps.upload-pinata.outputs.hash }}"
      - run: echo "CIDv1:${{ steps.upload-pinata.outputs.cid }}"
      - run: echo "ipfs:${{ steps.upload-dweb.outputs.ipfs }}"
      - run: echo "IPNS:${{ steps.upload-dweb.outputs.ipns }}"
