name: Release
on:
  # manual trigger
  workflow_dispatch:

jobs:
  publish:
    name: Publicar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pin to IPFS
        id: upload
        uses: aquiladev/ipfs-action@master
        with:
          pinName: biokaos-dcentralized
          path: './w3-mibalx'
          service: pinata
          pinataKey: ${{ secrets.PINATA_API_KEY }}
          pinataSecret: ${{ secrets.PINATA_API_SECRET_KEY }}
          
      - run: echo "ipfs:${{ steps.upload.outputs.hash }}"
      - run: echo "CIDv1:${{ steps.upload.outputs.cid }}"
      - run: echo "IPNS:${{ steps.upload.outputs.ipns }}"
